Update access-control.yaml after the Atala team restructure
hyperledger/governance pull request #335
Opened 2024-10-07 07:22 UTC by yshyn-iohk

2024-10-07 08:20 UTC, FabioPinheiro commented on access-control.yaml
> +      - bgravenors
missing a `t`

2024-10-07 08:28 UTC, FabioPinheiro commented
Any one you remove from `identus-admins` should go to `identus-maintainers`?
I wouldn't change anything in `identus-maintainers` for now

2024-10-07 11:26 UTC, ryjones requested changes
This seems fairly sloppy. please carefully review your changes.

2024-10-07 11:26 UTC, ryjones commented on access-control.yaml
> -      - mbrandenburger
why

2024-10-07 14:11 UTC, tkuhrt commented
It would be great if you can explain this change. This seems like you are completely restructuring maintainers of the project. We will need all existing maintainers to weigh in on these changes.

2024-10-07 16:24 UTC, yshyn-iohk commented on access-control.yaml
> -      - mbrandenburger
Sorry, my bad
thanks for fixing

2024-10-07 16:32 UTC, yshyn-iohk commented
I replaced `essbante-io` GitHub id with mine in the identus-maintainers team.
All other people were let go when the Atala Tribe was restructured:
- CryptoKnightIOG
- EzequielPostan
- FayyaadhAdams
- blockchaintimothy
- cristianIOHK
- curtis-h
- lohanspies
- milosbackonja
- milosh86
- mkbreuningIOHK
- patlo-iog
- petevielhaber
- shotexa
- womfoo
- Dale-iohk
- urosmrvic-iohk
- jesusdiazvico
- mattklepp

2024-10-07 16:35 UTC, yshyn-iohk commented on access-control.yaml
> +      - bgravenors
Thanks, @FabioPinheiro. My bad.

2024-10-07 16:35 UTC, yshyn-iohk commented
`bgravenorst` - was touched by me unintentionally

2024-10-08 08:56 UTC, yshyn-iohk commented
https://github.com/hyperledger/governance/pull/336 is the new PR according to the changes in the Atala

2024-10-08 08:57 UTC, closed without merging